.github/scripts/collect_metrics.py
.github/workflows/collect_metrics.yml

add metric collector

---

Getting_Started.md
firestore.rules
src/App.js
src/components/admin/UserPermissionDialog.js
src/components/layout/Navbar.js
src/components/routing/ProtectedRoute.js
src/constants/permissionsConstants.js
src/contexts/AuthContext.js
src/pages/AdminPage.js
src/pages/UnauthorizedPage.js
src/services/firebaseService.js

Add Auth/admin panel

---

src/App.js
src/components/agents/AgentReasoningLogDialog.js
src/components/agents/AgentRunner.js
src/components/agents/RunHistory.js
src/components/agents/RunHistoryItem.js
src/components/common/MuiMarkdownComponents.js
src/components/tools/ToolSelector.js
src/pages/AgentPage.js

Thoughts in response
Load History
Cleaned up tools

Fixed Platform Redirects

---

functions/.gitignore
functions/common/adk_helpers.py
functions/handlers/vertex/deployment_logic.py
functions/handlers/vertex/query_logic.py
src/components/agents/AgentDetailsDisplay.js
src/components/agents/AgentForm.js
src/components/agents/AgentListItem.js
src/components/agents/ChildAgentFormDialog.js
src/constants/agentConstants.js
src/pages/AgentPage.js
src/pages/CreateAgentPage.js

LiteLLM 'works' now but is uber hacky

---

.github/workflows/deploy-functions.yml

Syntax fix in autodeploy workflow
List any linked issues or PRs:

syntax fix in autodeploy workflow

---

functions/common/adk_helpers.py
functions/handlers/vertex/deployment_logic.py
functions/handlers/vertex/query_logic.py
functions/main.py
src/constants/agentConstants.js

LiteLLM still isn't perfect, but together_ai and openAi work now. 
* What changes were made?
* Why are they the correct solution?
* Any design decisions worth noting?
List any linked issues or PRs:
Closes #57 
* Unit tests added/updated
* Manual verification steps
* Any automated test coverage
* Links to discussions, decisions, or resources
* Known limitations or follow-up tasks

TogetherAI works now

---

.github/workflows/upstream-pr-checks.yml

Linting always fails on PRs (because it isn't set up)
I spent a couple of hours going down the rabbit hole of react linting and testing and getting wierder and wierder errors, so eventually i just gave up and commented out the tests. 
Related to #33 
Tests were disabled. 
Create two new issues, one to setup testing, one to setup linting.

Silence the linting and testing

---

.github/workflows/deploy-functions.yml

Fixes these issues:
Fix deploy-functions workflow Add step to copy ADC file during function deployment
Load secrets into functions/.env file before deployment
List any linked issues or PRs:
Fixes #72
Fixes #71 
* Unit tests added/updated
* Manual verification steps
* Any automated test coverage
* Links to discussions, decisions, or resources
* Known limitations or follow-up tasks

Fixes deploy-function workflow

---

firestore.rules
src/components/agents/AgentListItem.js
src/components/agents/ExistingAgentSelectorDialog.js
src/components/agents/RunHistoryItem.js
src/pages/AgentPage.js
src/pages/DashboardPage.js
src/services/firebaseService.js

Adds the ability to
1. make agents public on the deployment
2. copy existing agents into new agents
3. save agent to local / upload local json to make new agent.
Closes #56 
Check all areas affected by this feature:
| Before | After |
|--------|-------|
| Image or description | Image or description |
Confirm the tests conducted to validate this feature:
Verify documentation was updated accordingly:
Ensure deployment readiness:
Any other relevant information for reviewers, known issues, or follow-up tasks.

Clonable / Shareable / Portable Agents

---

public/version.json
src/App.js
src/components/layout/Navbar.js
src/pages/AboutPage.js
src/pages/DashboardPage.js

This PR adds an about page, which displays information from appConfig.json, as well as the version from version.json
A follow on PR will create 'releases' and reflect the release number to version.json. 
This will help down stream users know how far behind the main they are (and what features may be missing because of that lag)
Closes #69 
Check all areas affected by this feature:
Confirm the tests conducted to validate this feature:
Verify documentation was updated accordingly:
Ensure deployment readiness:
Any other relevant information for reviewers, known issues, or follow-up tasks.

Add about page

---

.github/workflows/sync-upstream.yml
docs/syncing.md

Allows the maintainer of a fork the ability to sync with an upstream based on a specific tag, while maintaining local (to the fork) edits.
Check all areas affected by this feature:
Confirm the tests conducted to validate this feature:
Verify documentation was updated accordingly:
Ensure deployment readiness:
Any other relevant information for reviewers, known issues, or follow-up tasks.

Workflow to Sync Upstream

---

Getting_Started.md
firestore.indexes.json

Updated docs as I did another deployment.
Also we need an action to build the indexes (or maybe a script to do the entire deployment?)
Indicate the type of documentation updates:
| Before | After |
|--------|-------|
| Old content | New content |
Confirm the following items were reviewed:
List any specific modules, files, or UI elements impacted by these changes.
Provide any other context, references, or discussions relevant to this documentation update.

[DOCS] Update deployment instructions and add indexes

---

functions/common/adk_helpers.py
functions/handlers/mcp_handler.py
functions/handlers/vertex/deployment_logic.py
functions/handlers/vertex/management_logic.py
functions/handlers/vertex/query_local_diagnostics.py
functions/main.py
functions/requirements.txt
src/components/agents/AgentForm.js
src/components/agents/AgentRunner.js
src/components/agents/ChildAgentFormDialog.js
src/components/tools/McpAuthDialog.js
src/components/tools/ToolSelector.js
src/constants/platformConstants.js
src/services/agentService.js

Removes ADK Built in tools in favor of 'Add MCP Server' And auth is _somewhat_ supported. Auth on MCP is kinda all over the place so for some it will work, some it won't i anticipate bugs and patches as that stabilizes. 
User can now add an MCP server, it will list the tools, then select one and it will work.
Closes #61 Which was the main idea
Closes #54 Because I was there. 
Also Closes #83 because it was bugging me. 
Check all areas affected by this feature:
| Before | After |
|--------|-------|
| Image or description | Image or description |
Auth (unrequired for fetch)
Confirm the tests conducted to validate this feature:
Verify documentation was updated accordingly:
Ensure deployment readiness:
Any other relevant information for reviewers, known issues, or follow-up tasks.

Add MCP as a tool source

---

functions/handlers/vertex/query_orchestrator.py
functions/handlers/vertex/query_vertex_runner.py
src/components/agents/AgentRunner.js
src/components/agents/RunHistoryItem.js

Various regressions/bugs in the reasoning log
1. REGRESSION: I think from when the back end got refactored- reasoning logs always say "No Content"
2. BUG: The 'type' field was always 'unknown' now it is filled- see photos below
3. REGRESSION: Probably related to 1, when you loaded run history it wouldn't show the reasoning logs at all.
See the files
No, i was lzay.
Manual.
* Links to discussions, decisions, or resources
* Known limitations or follow-up tasks

Event/Reasoning Log Clean up

---

functions/handlers/vertex/task_handler.py

#95 introduced a regression on individual models- this fixes.

Regression on model only runs- fixed

---

Getting_Started.md
firestore.indexes.json

Closes https://github.com/The-AI-Alliance/agent-lab-ui/issues/94 - Update Getting Started Documents. Two changes to ./Getting_Started.md
1. JSON double quotes around firebaseConfig json
2. Added Owner as an IAM Role, denoting it should probably be looked at
Indicate the type of documentation updates:
Documentation changes verified visually.

Closes #94 - Update Getting Started Documents

---

src/components/agents/AgentList.js
src/components/agents/AgentListItem.js
src/pages/AgentsPage.js
src/services/firebaseService.js

Copy button and 'Make Public' switch got lost in refactor- this adds them back
* What changes were made?
* Why are they the correct solution?
* Any design decisions worth noting?
Closes #106
* Unit tests added/updated
* Manual verification steps
* Any automated test coverage
* Links to discussions, decisions, or resources
* Known limitations or follow-up tasks

Add Copy and Make Public buttons back

---

functions/handlers/vertex/query_orchestrator.py
functions/handlers/vertex/task_handler.py

backend updates

---

functions/common/adk_helpers.py
functions/common/config.py
functions/handlers/__init__.py
functions/handlers/a2a_handler.py
functions/handlers/context_handler.py
functions/handlers/mcp_handler.py
functions/handlers/vertex/deployment_logic.py
functions/handlers/vertex/query_local_diagnostics.py
functions/handlers/vertex/query_orchestrator.py
functions/handlers/vertex/query_session_manager.py
functions/handlers/vertex_agent_handler.py
functions/main.py

liposuction on functions directory

---

functions/handlers/vertex/task/__init__.py
functions/handlers/vertex_agent_handler.py
functions/main.py
src/constants/agentConstants.js

125 - Load Full History

---

firestore.rules

Anyone who can create a project can delete a project

---

functions/requirements.txt

Fixes #130 
The issue was a breaking change in google-adk. I opened an issue here https://github.com/google/adk-python/issues/2361

Pin google-adk version

---

.github/workflows/deploy-functions.yml
.github/workflows/deploy-indexes-and-rules.yml
firestore.indexes.json

Fixes #142 Pick up Env Secrets in Github Actions Deploy Functions
Fixes #144 Revert Indexes to Previous Hash
* What changes were made?
* Why are they the correct solution?
* Any design decisions worth noting?
List any linked issues or PRs:
* Issue references (e.g., #123)
* Related PRs (if applicable)
* Unit tests added/updated
* Manual verification steps
* Any automated test coverage
* Links to discussions, …

Small fixes

---

README.md

Added section in readme for new changes.
| Before | After |
|--------|-------|
| Old content | New content |
Confirm the following items were reviewed:
List any specific modules, files, or UI elements impacted by these changes.
Provide any other context, references, or discussions relevant to this documentation update.

section about agents, projects, models

---

src/constants/agentConstants.js

Add Llama 4 options for Meta Llama

---

functions/handlers/context_handler.py
src/components/context_stuffing/GitRepoContextModal.js
src/services/contextService.js

Fixes #148 
Allows user to specify branch when loading a git repo- defaults to main
---

Specify branch when loading a git repo for context

---

src/constants/agentConstants.js

Fixes #160 
Updates anthropic models, but also updates gemini models since i was there anyway
---

Update anthropic and google models

---

firestore.rules
public/appConfig.json
src/App.js
src/pages/ChatPage.js
src/services/firebaseService.js

feat: Share Chats

---

functions/requirements.txt

Clean up all the hacks in requirements.txt
---

cleanup requirements.txt

---

src/components/agents/AgentForm.js
src/components/agents/ChildAgentFormDialog.js
src/utils/agentValidation.js

Fix: Refactor duplicate code

---

functions/handlers/vertex/task/agent_runner.py

Reverts The-AI-Alliance/agent-lab-ui#191

Revert "BUG: Drop Asyncy"

---

functions/handlers/vertex/task/agent_runner.py
src/hooks/useChatManager.js
src/services/chatService.js

Hotfix async issue

---

src/hooks/useChatManager.js

hotfix: es-lint ignore
